[package]
name = "modules"
version = "0.0.2"
edition = "2024"
repository = "https://github.com/DrWursterich/lspml/modules"
license = "MIT"

[dependencies]
anyhow = "1.0.79"
log = "0.4.20"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.140"
