[package]
name = "lspml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
httparse = "1.8.0"
lsp-server = "0.7.6"
lsp-types = "0.95.0"
serde = "1.0.194"
serde_json = "1.0.111"
tokio = { version = "1.35.1", features = ["full"] }
tower-lsp = "0.20.0"
tree-sitter = "0.20.10"
tree-sitter-html = "0.19.0"

[dev-dependencies]
tokio-test = "0.4.3"
