[package]
name = "derive"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.79"
log = "0.4.20"
proc-macro2 = "1.0.81"
quote = "1.0"
syn = "2.0"
tree-sitter = "0.23.0"
tree-sitter-spml = { git = "https://github.com/DrWursterich/tree-sitter-spml.git" }

