[package]
name = "derive"
version = "0.0.2"
edition = "2024"
repository = "https://github.com/DrWursterich/lspml/derive"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.79"
proc-macro2 = "1.0.81"
quote = "1.0"
syn = "2.0"
